### ISSUE TITLE
Task List markdown output is incorrect

### ISSUE THREAD

**Issue by krissrex** [egoist/eme#113]
Bug: using task lists `- [ ] task` will html encode the `<` and `>` of the input tag
Expected: should not encode `<` and `>`, so that the tag becomes an DOM element instead of text

![image](https://cloud.githubusercontent.com/assets/7364831/21363432/e0796054-c6ec-11e6-9715-8953a539af72.png)

The html for the `li` generated for  `- [ ] hey` is this:

```html
<li class="task-list-item">&lt;input class="task-list-item-checkbox" disabled="" type="checkbox"&gt; hey</li>
```

when it should have been:

```html
<li class="task-list-item"><input class="task-list-item-checkbox" disabled="" type="checkbox"> hey</li>
```

**Comment by kingdido999** [comment]
This issue is caused by the introduction of [markdown-it-sanitizer](https://github.com/svbergerem/markdown-it-sanitizer) in commit [63e2ec8](https://github.com/egoist/eme/commit/63e2ec88423adc51c150c42e93d379b250510dac). From my understanding, `<input>` is not a whitelisted tag so the sanitizer will treat it as an unknown tag and outputs:

```html
&lt;input class="task-list-item-checkbox" disabled="" type="checkbox"&gt; hey
```

instead of:

```html
<input class="task-list-item-checkbox" disabled="" type="checkbox"> hey
```

After removing the sanitizer, it works fine.

**Comment by egoist** [comment]
@kingdido999 Yep, we can drop this since we just want to filter xss, do you have a better solution?

**Comment by egoist** [comment]
I've fixed this by using a custom sanitizer https://github.com/egoist/eme/blob/dev/src/utils/sanitize.js
